# Generated by Django 3.2.8 on 2021-11-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=100)),
                ('ids', models.TextField(default='')),
                ('photo_type', models.CharField(default='S', max_length=1)),
                ('fields', models.TextField(default='')),
                ('limit_groups', models.IntegerField(default=0)),
                ('limit_members', models.IntegerField(default=0)),
                ('limit_photos', models.IntegerField(default=0)),
                ('limit_posts', models.IntegerField(default=0)),
                ('hard_limit_posts', models.IntegerField(default=0)),
                ('interpreted_chain', models.TextField(default='')),
                ('remaining_chain', models.TextField(default='')),
                ('progress', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
            ],
        ),
    ]
