# Generated by Django 3.2.8 on 2021-11-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='current_tokens',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='is_need_to_reload_tokens',
            field=models.BooleanField(default=False),
        ),
    ]
