# Generated by Django 3.2.8 on 2021-11-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211111_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='original_chain',
            field=models.TextField(default=''),
        ),
    ]
