# Generated by Django 3.2.8 on 2021-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20211112_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='errors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=85, verbose_name='Token'),
        ),
    ]
