name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint-django
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(find . -path "./main/*" -not -path "./main/migrations/*" -name "*.py" | xargs) --max-line-length=120 --load-plugins=pylint_django --django-settings-module=VKDumperWeb.settings --ignore-imports=yes
